// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn2JFQT9gOoFuVFK7tYGI_3gXG4EqcVGQ',
    appId: '1:980447469808:web:6e58e0236693de5d666235',
    messagingSenderId: '980447469808',
    projectId: 'sabrina-app',
    authDomain: 'sabrina-app.firebaseapp.com',
    storageBucket: 'sabrina-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBrdkE_RImuD8MZF0bKy8KufpD2n1l7WQ',
    appId: '1:980447469808:android:3937bb4d9ac97188666235',
    messagingSenderId: '980447469808',
    projectId: 'sabrina-app',
    storageBucket: 'sabrina-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0n57ak8QHLSNINV6Z-UcpJqf83GY8o0',
    appId: '1:980447469808:ios:db74bbd449aa3216666235',
    messagingSenderId: '980447469808',
    projectId: 'sabrina-app',
    storageBucket: 'sabrina-app.appspot.com',
    iosClientId: '980447469808-h7jnl395pgbcdpm5fj3km6s9tafe1g4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointmentAppMainTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0n57ak8QHLSNINV6Z-UcpJqf83GY8o0',
    appId: '1:980447469808:ios:db74bbd449aa3216666235',
    messagingSenderId: '980447469808',
    projectId: 'sabrina-app',
    storageBucket: 'sabrina-app.appspot.com',
    iosBundleId: 'com.example.doctorAppointmentAppMainTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn2JFQT9gOoFuVFK7tYGI_3gXG4EqcVGQ',
    appId: '1:980447469808:web:bca3cf34515eb4ac666235',
    messagingSenderId: '980447469808',
    projectId: 'sabrina-app',
    authDomain: 'sabrina-app.firebaseapp.com',
    storageBucket: 'sabrina-app.appspot.com',
  );

}